/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ivizon_androidcomputesample_NativeComputeLoad */

#ifndef _Included_com_ivizon_androidcomputesample_NativeComputeLoad
#define _Included_com_ivizon_androidcomputesample_NativeComputeLoad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ivizon_androidcomputesample_NativeComputeLoad
 * Method:    initBoostCompute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ivizon_androidcomputesample_NativeComputeLoad_initBoostCompute
  (JNIEnv *, jclass);

/*
 * Class:     com_ivizon_androidcomputesample_NativeComputeLoad
 * Method:    getDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ivizon_androidcomputesample_NativeComputeLoad_getDeviceName
  (JNIEnv *, jclass);

/*
 * Class:     com_ivizon_androidcomputesample_NativeComputeLoad
 * Method:    getComputeUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ivizon_androidcomputesample_NativeComputeLoad_getComputeUnits
  (JNIEnv *, jclass);

/*
 * Class:     com_ivizon_androidcomputesample_NativeComputeLoad
 * Method:    getGlobalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ivizon_androidcomputesample_NativeComputeLoad_getGlobalMemory
  (JNIEnv *, jclass);

/*
 * Class:     com_ivizon_androidcomputesample_NativeComputeLoad
 * Method:    getLocalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ivizon_androidcomputesample_NativeComputeLoad_getLocalMemory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
