#!/usr/bin/python
import os
import sys
import argparse
import shutil
from subprocess import call

ROOT = None


def sync_submodules():
    print '---------------- Start syncing submodules ----------------'
    # Fetch submodules
    os.chdir(ROOT)
    call(['git', 'submodule', 'update', '--init', '--recursive'])

    if os.path.exists('CL-12'):
        print 'CL-12 has existed already'
    else:
        print 'Download OpenCL 1.2 Headers..................'
        call(['sh', 'get_opencl.sh'])

    print 'Download Boost 1.55.0..................'
    boost_path = os.path.join(ROOT, 'third-party', 'Boost-for-Android')
    boost_source_folder = os.path.join(boost_path, 'boost_1_55_0')
    os.chdir(boost_path)
    if os.path.exists(boost_source_folder):
        print 'boost has existed already'
    else:
        call(['sh', 'download-boost.sh'])

    print '---------------- End   syncing submodules ----------------'

def main(argv):
    global ROOT
    ROOT = os.path.dirname(os.path.abspath(__file__))
    sync_submodules()

if __name__ == '__main__':
    main(sys.argv[1:])
